export const INITIAL_BOARD_STATE = {
  tiles: {
    A: { pressed: false },
    B: { pressed: false },
    C: { pressed: false },
    D: { pressed: false },
    E: { pressed: false },
    Y: { pressed: false },
    F: { pressed: false },
    W: { pressed: false },
    G: { pressed: false },
    V: { pressed: false },
    H: { pressed: false },
    U: { pressed: false },
    I: { pressed: false },
    T: { pressed: false },
    J: { pressed: false },
    S: { pressed: false },
    K: { pressed: false },
    R: { pressed: false },
    L: { pressed: false },
    Q: { pressed: false },
    P: { pressed: false },
    O: { pressed: false },
    N: { pressed: false },
    M: { pressed: false },
    "": { pressed: false },
  },
  tilesPressed: 0,
  contestableLetter: "",
};

export const TIMEOUT = 5;
